# -*- coding: utf-8 -*-
"""ESG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1didcFxwP3_Ekjxv5s3gHXaaCgPITE-5L
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

all_inport_df = pd.read_csv('data/cleaned_all_inport.csv')

display(all_inport_df.head())
all_inport_df.info()

final_port_month_df = pd.read_csv('data/final_port_month.csv')
display(final_port_month_df.head())
final_port_month_df.info()

"""依據 IMO 標準，定義碳排計算函數"""

import numpy as np
import pandas as pd

def estimate_vessel_co2(row):
    """
    依據 IMO (國際海事組織) 經驗公式，估算單次進港的輔機與鍋爐總碳排 (公噸)
    """
    gt = row['gross_tonnage']
    v_type = str(row['vessel_type_group']).lower()

    # 預設值（若無法辨識船型時使用）
    ae_power = 2.12 * (gt ** 0.55) if gt > 0 else 0
    load_berth = 0.4
    load_anchor = 0.2

    # 依據船型給定不同的 IMO 功率迴歸公式與負載因子
    if 'container' in v_type:          # 貨櫃船 (耗電極大)
        ae_power = 0.45 * (gt ** 0.85)
        load_berth, load_anchor = 0.55, 0.25
    elif 'bulk' in v_type:             # 散裝船
        ae_power = 2.12 * (gt ** 0.55)
        load_berth, load_anchor = 0.40, 0.20
    elif 'tanker' in v_type:           # 油輪
        ae_power = 14.7 * (gt ** 0.42)
        load_berth, load_anchor = 0.45, 0.20
    elif 'passenger' in v_type:        # 客輪/郵輪 (生活用電高)
        ae_power = 0.25 * (gt ** 0.90)
        load_berth, load_anchor = 0.60, 0.30

    # 國際標準常數
    sfc = 210           # 燃油消耗率 (g/kWh)
    cf = 3.114          # 碳轉換因子 (每噸油產生 3.114 噸 CO2)

    # 讀取時間 (若為 NaN 則補 0)
    b_hours = row['berth_wait_hours'] if pd.notna(row['berth_wait_hours']) else 0
    a_hours = row['anchor_wait_hours'] if pd.notna(row['anchor_wait_hours']) else 0

    # 分別計算碼頭與錨區的碳排放 (單位：公噸)
    co2_berth = b_hours * ae_power * load_berth * sfc * cf / 1000000
    co2_anchor = a_hours * ae_power * load_anchor * sfc * cf / 1000000

    return co2_berth + co2_anchor

# 執行計算：建立新欄位 'estimated_co2'
all_inport_df['estimated_co2'] = all_inport_df.apply(estimate_vessel_co2, axis=1)

print("碳排放估算完成！前三筆結果：")
display(all_inport_df[['vessel_type_group', 'gross_tonnage', 'berth_wait_hours', 'anchor_wait_hours', 'estimated_co2']].head(3))

"""將油價與衝擊資訊合併"""

# 1. 取出第一份資料的背景特徵，並去除重複值
oil_meta = final_port_month_df[['port', 'year_month', 'oil_price', 'oil_change_pct', 'any_shock', 'event_name']].drop_duplicates()

# 2. 以 port 和 year_month 為 Key 進行合併
analysis_df = all_inport_df.merge(oil_meta, on=['port', 'year_month'], how='left')

print("資料合併完成，目前總筆數：", analysis_df.shape[0])

"""開始進行數據分析與視覺化"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
# 為了避免極端異常值影響視覺化，限制 y 軸在 95 百分位數內
y_limit = analysis_df['estimated_co2'].quantile(0.95)

sns.scatterplot(
    data=analysis_df[analysis_df['estimated_co2'] <= y_limit],
    x='oil_price',
    y='estimated_co2',
    hue='any_shock',
    alpha=0.4
)
plt.title('Relationship between Oil Price and Vessel CO2 Emissions in Ports')
plt.xlabel('Oil Price')
plt.ylabel('Estimated CO2 per Arrival (Tons)')
plt.show()

"""統計迴歸分析"""

import statsmodels.api as sm
import statsmodels.formula.api as smf

# 排除缺失值
regression_data = analysis_df.dropna(subset=['estimated_co2', 'oil_price', 'gross_tonnage', 'vessel_type_group', 'port']).copy()

# 建立迴歸模型，控制船隻大小(gross_tonnage)與港口結構、船型定義
# C(port) 和 C(vessel_type_group) 會自動轉為虛擬變數（控制固定效應）
model = smf.ols('estimated_co2 ~ oil_price + gross_tonnage + C(port) + C(vessel_type_group)', data=regression_data)
results = model.fit()

print(results.summary())

import statsmodels.formula.api as smf

# 排除缺失值，並確保 year 和 month 存在以控制時間固定效應
regression_data_v2 = analysis_df.dropna(
    subset=['estimated_co2', 'oil_price', 'any_shock', 'gross_tonnage', 'vessel_type_group', 'port', 'year', 'month']
).copy()

# 建立交互項迴歸模型
# oil_price * any_shock 系統會自動拆解為三個部分：
# 1. oil_price 獨立效應
# 2. any_shock 獨立效應
# 3. oil_price:any_shock 交互作用效應 (這最關鍵！)
# 同時加入 C(year) + C(month) 來控制時間固定效應，提升 R平方 (解釋力)

model_v2 = smf.ols(
    'estimated_co2 ~ oil_price * any_shock + gross_tonnage + C(port) + C(vessel_type_group) + C(year) + C(month)',
    data=regression_data_v2
)
results_v2 = model_v2.fit()

print(results_v2.summary())

from scipy import stats

# 分割成有戰爭衝擊與沒衝擊的月份油價
shock_oil = final_port_month_df[final_port_month_df['any_shock'] == 1]['oil_price'].dropna()
normal_oil = final_port_month_df[final_port_month_df['any_shock'] == 0]['oil_price'].dropna()

t_stat, p_val = stats.ttest_ind(shock_oil, normal_oil, equal_var=False)
print(f"戰爭月份平均油價: {shock_oil.mean():.2f} 美元")
print(f"正常月份平均油價: {normal_oil.mean():.2f} 美元")
print(f"T檢定 P值: {p_val:.4f}")