# -*- coding: utf-8 -*-
"""Visualization Big Data G7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kpz03VVdCKWx7QMkss37h-fGMqMWQmyV

### Load Data
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

all_inport_df = pd.read_csv('data/cleaned_all_inport.csv')

display(all_inport_df.head())
all_inport_df.info()

final_port_month_df = pd.read_csv('data/final_port_month.csv')
display(final_port_month_df.head())
final_port_month_df.info()

"""### Vessel Type Composition Per Port

This section analyzes the distribution of different vessel types for each port, showing what kind of traffic each port primarily handles.
"""

port_vessel_composition = all_inport_df.groupby(['port', 'vessel_type_group']).size().unstack(fill_value=0)

# Calculate percentages for each port
port_vessel_percentage = port_vessel_composition.apply(lambda x: x / x.sum() * 100, axis=1)

display(port_vessel_percentage.round(2))

import matplotlib.pyplot as plt
import seaborn as sns

port_map_en = {
    '基隆港': 'Keelung',
    '臺北港': 'Taipei',
    '花蓮港': 'Hualien',
    '高雄港': 'Kaohsiung'
}
port_vessel_percentage_plot = port_vessel_percentage.rename(index=port_map_en)

# Stacked bar chart
fig, ax = plt.subplots(figsize=(10, 6))
port_vessel_percentage_plot.plot(kind='bar', stacked=True, colormap='viridis', ax=ax)

plt.title('Vessel Type Composition by Port (Percentage)', fontsize=16)
plt.xlabel('Port', fontsize=12)
plt.ylabel('Percentage (%)', fontsize=12)
plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for readability
plt.legend(title='Vessel Type Group', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""**Keelung Port:** Primarily handles Container vessels (around 53.80%), followed by Dry Cargo (13.75%) and Bulk (11.08%).

**Taipei Port:** Also has a significant share of Container vessels (41.61%), but shows a more diversified composition with a notable presence of 'Other' vessel types (21.50%) and Dry Cargo (17.50%).

**Hualien Port:** This port is distinctive, with Bulk vessels making up the largest share (40.72%), followed by Dry Cargo (28.61%) and 'Other' (23.38%). It's notable that Hualien does not show any Container vessel arrivals in this aggregated view.

**Kaohsiung Port:** As a major hub, Kaohsiung has the highest percentage of Container vessels (49.90%), along with significant numbers of Bulk (24.71%) and Tanker (13.90%) arrivals.

 Kaohsiung and Keelung handles a high volume of container traffic, while Hualien focuses more on bulk and dry cargo. Taipei also has significant container traffic but a more diverse set of 'other' vessels.

### Overall Port Sensitivity to Oil Shocks

This section analyzes the overall change in average monthly vessel arrivals for each port during periods of oil price shocks, providing a high-level view of how each port's traffic, influenced by its unique vessel composition, reacts to such events.
"""

# Calculate total arrivals per port during shock vs non-shock
port_overall_shock_stats = final_port_month_df.groupby(['port', 'oil_shock'])['arrivals'].mean().unstack()

# Calculate Percentage Change for each port
port_overall_shock_stats['pct_change'] = ((port_overall_shock_stats[1] - port_overall_shock_stats[0]) / port_overall_shock_stats[0]) * 100

print("Overall Port Sensitivity to Oil Shocks (Percentage Change in Average Monthly Arrivals):")
display(port_overall_shock_stats)

# Mapping from Chinese to English
port_map_en = {
    '基隆港': 'Keelung',
    '臺北港': 'Taipei',
    '花蓮港': 'Hualien',
    '高雄港': 'Kaohsiung'
}

# Prepare data for visualization
port_overall_shock_stats_plot = port_overall_shock_stats.reset_index()
port_overall_shock_stats_plot['port_en'] = port_overall_shock_stats_plot['port'].map(port_map_en)

"""### Sensitivity Analysis: Impact of Oil Shocks by Port and Vessel Type

This section analyzes the percentage change in vessel arrivals for each vessel type (e.g., Container ships, Bulk carriers) within each port during periods of oil price shocks.
"""

# 1. Prepare monthly vessel type counts from all_inport_df
vessel_type_monthly = all_inport_df.groupby(['port', 'year_month', 'vessel_type_group']).size().reset_index(name='arrival_count')

# 2. Merge with oil shock indicators from final_port_month_df
# Ensure year_month is string
vessel_type_monthly['year_month'] = vessel_type_monthly['year_month'].astype(str)
final_port_month_df['year_month'] = final_port_month_df['year_month'].astype(str)
shock_info = final_port_month_df[['port', 'year_month', 'oil_shock']].drop_duplicates()

merged_vessel_type_shock_df = pd.merge(
    vessel_type_monthly,
    shock_info,
    on=['port', 'year_month'],
    how='left'
)

# Handle  NaN oil_shock values
merged_vessel_type_shock_df['oil_shock'] = merged_vessel_type_shock_df['oil_shock'].fillna(0) # Assume no shock if info missing

# 3. Calculate average arrivals per vessel_type_group during Shock vs. Non-Shock for each port
port_vessel_type_shock_stats = merged_vessel_type_shock_df.groupby(['port', 'vessel_type_group', 'oil_shock'])['arrival_count'].mean().unstack()

# 4. Calculate Percentage Change
# (Mean_Shock - Mean_NoShock) / Mean_NoShock * 100
port_vessel_type_shock_stats['pct_change'] = ((port_vessel_type_shock_stats[1] - port_vessel_type_shock_stats[0]) / port_vessel_type_shock_stats[0]) * 100

# 5. Prepare data for display and visualization
port_vessel_type_results = port_vessel_type_shock_stats.reset_index()
port_vessel_type_results['port_en'] = port_vessel_type_results['port'].map(port_map_en)

display(port_vessel_type_results[['port_en', 'vessel_type_group', 'pct_change']])

# 6. Visualization
plt.figure(figsize=(10, 6))
sns.barplot(x='port_en', y='pct_change', hue='vessel_type_group', data=port_vessel_type_results, palette='tab10')
plt.axhline(0, color='black', linewidth=1)
plt.title('Percentage Change in Arrivals During Oil Shocks by Port and Vessel Type', fontsize=14)
plt.ylabel('Change in Arrivals (%)')
plt.xlabel('Port')
plt.legend(title='Vessel Type Group', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Analysis of Oil Shock Impact by Port and Vessel Type

*   **Keelung Port:**
    *   **Bulk & Container:** Shows a slight increase for Bulk (2.30%) but a minor decrease for Container (-0.85%). This suggests a relatively stable response or slight shifts in cargo types.
    *   **Dry Cargo & Passenger:** Experience significant declines (-6.40% and -48.28% respectively), indicating these vessel types are highly vulnerable to oil shocks in Keelung.
    *   **Other:** A notable drop of -27.90% for 'Other' vessel types, suggesting this heterogeneous group includes vessels sensitive to economic disruptions.

*   **Taipei Port:**
    *   **Consistent Declines:** Most vessel types show double-digit percentage drops, especially for Bulk (-17.91%), Dry Cargo (-16.90%), and Container (-13.06%). This highlights Taipei's broader vulnerability across its major vessel segments during oil shocks.
    *   **Other:** Also sees a substantial decrease of -16.48%.

*   **Hualien Port:**
    *   **Bulk & Dry Cargo:** Both primary vessel types for Hualien show significant negative impacts (-15.82% for Bulk, -26.96% for Dry Cargo), underscoring the port's sensitivity to oil shocks in its core operations.
    *   **Passenger & Other:** 'Passenger' traffic drops by -42.86%, while surprisingly, 'Other' vessels show a substantial increase (92.45%), which might indicate specific types of vessels or activities in the 'Other' category that are less affected or even increase during such times, possibly due to rerouting or specialized cargo demands.

*   **Kaohsiung Port:**
    *   **Resilience in Major Types:** As a major international hub, Kaohsiung demonstrates remarkable stability. Container, Bulk, and Dry Cargo show only minor percentage changes (e.g., Container -1.25%, Bulk -2.98%), indicating these essential services are largely maintained despite oil shocks.
    *   **Tankers:** Tanker arrivals in Kaohsiung show a positive change of 6.14%, suggesting either increased demand for oil transportation or strategic routing to this major port during periods of volatility.

**Overall Insights:**

*   **Differentiated Impact:** The impact of oil shocks is not uniform; it varies significantly by port and vessel type, reflecting their unique operational characteristics and economic roles.
*   **Vulnerability of Passenger & Dry Cargo:** Passenger and Dry Cargo vessels tend to be more sensitive, experiencing larger percentage declines across multiple ports.
*   **Kaohsiung's Stability:** Kaohsiung's container and bulk traffic shows strong resilience, underscoring its critical role in global supply chains.
*   **'Other' Category Volatility:** The 'Other' vessel type often exhibits extreme changes (both positive and negative), warranting further investigation into its composition during different economic conditions.

### Arrival Frequency Trends by Vessel Type with Shock/Recovery

Changes in arrival frequency for different vessel types (e.g., Bulk, Container) within each port during oil price shock periods (red) and the subsequent three-month recovery periods (green).
"""

# 1. Prepare data using vessel_type_monthly (port, year_month, vessel_type_group, arrival_count)
vt_plot_df = vessel_type_monthly.copy()
vt_plot_df['date'] = pd.to_datetime(vt_plot_df['year_month'])

# 2. Add oil_shock info from shock_info
shock_info_subset = final_port_month_df[['port', 'year_month', 'oil_shock']].drop_duplicates()
shock_info_subset['date'] = pd.to_datetime(shock_info_subset['year_month'])

vt_plot_df = pd.merge(
    vt_plot_df,
    shock_info_subset[['port', 'date', 'oil_shock']],
    on=['port', 'date'],
    how='left'
)

# 3. Label regimes (Shock/Recovery/Normal) using a 3-month recovery window
def label_regimes_vt(group, n_recovery=3):
    group = group.sort_values('date').copy()
    group['regime'] = 'Normal'
    group.loc[group['oil_shock'] == 1, 'regime'] = 'Shock'

    shock_mask = group['oil_shock'] == 1
    starts = group.index[shock_mask & (~shock_mask.shift(1, fill_value=False))]

    for start_idx in starts:
        idx_pos = group.index.get_loc(start_idx)
        end_pos = idx_pos
        # Find the end of continuous shock period
        while end_pos + 1 < len(group) and group['oil_shock'].iloc[end_pos + 1] == 1:
            end_pos += 1
        # Label subsequent months as Recovery
        for k in range(1, n_recovery + 1):
            pos = end_pos + k
            if pos >= len(group):
                break
            if group['regime'].iloc[pos] == 'Normal':
                group.iloc[pos, group.columns.get_loc('regime')] = 'Recovery'
    return group

vt_plot_df = vt_plot_df.groupby(['port', 'vessel_type_group'], group_keys=False).apply(label_regimes_vt)

# 4. Plot figure per port x vessel_type_group
for p in sorted(vt_plot_df['port'].unique()):
    port_en = port_map_en.get(p, str(p))
    for vt in sorted(vt_plot_df[vt_plot_df['port'] == p]['vessel_type_group'].unique()):
        sub = vt_plot_df[(vt_plot_df['port'] == p) & (vt_plot_df['vessel_type_group'] == vt)].sort_values('date')

        if sub.empty or sub['arrival_count'].sum() == 0:
            continue

        fig, ax = plt.subplots(figsize=(12, 4))
        ax.plot(sub['date'], sub['arrival_count'], color='teal', linewidth=1.5, label='Arrivals')

        # Shock and Recovery
        for regime, color, alpha in [('Shock', 'red', 0.15), ('Recovery', 'green', 0.10)]:
            mask = sub['regime'] == regime
            if not mask.any():
                continue
            group_id = (mask.ne(mask.shift(fill_value=False))).cumsum()
            for gid, gsub in sub[mask].groupby(group_id):
                ax.axvspan(gsub['date'].min(), gsub['date'].max(),
                           color=color, alpha=alpha,
                           label=regime if regime not in ax.get_legend_handles_labels()[1] else None)

        ax.set_title(f'{vt} Arrivals Trends with Shock / Recovery - {port_en}')
        ax.set_xlabel('Date')
        ax.set_ylabel('Arrival Count')
        ax.grid(True, linestyle='--', alpha=0.3)

        # Deduplicate legend
        handles, labels = ax.get_legend_handles_labels()
        by_label = dict(zip(labels, handles))
        ax.legend(by_label.values(), by_label.keys())

        plt.tight_layout()
        plt.show()

"""### Analysis of Arrival Frequency Trends by Vessel Type with Shock/Recovery

This section visually explores the monthly arrival trends for each vessel type at each port, highlighting periods of oil price 'Shock' (red) and subsequent 'Recovery' (green). The numerous plots generated provide a detailed, granular view of dynamic responses.

**Common Observations Across Plots:**

*   **Visible Impact of Shocks:** In many instances, the red-shaded 'Shock' periods visually correlate with dips or decelerations in arrival counts, particularly for **Passenger**, **Dry Cargo**, and **Bulk** vessels across various ports, and for **Container** vessels in Taipei. Conversely, **Tanker** arrivals in Kaohsiung and 'Other' vessels in Hualien sometimes show increases during shock periods. This reaffirms the quantitative findings from the previous sensitivity analysis.
*   **Recovery Patterns:** The green-shaded 'Recovery' periods often show a rebound in arrival numbers, or a stabilization after a shock-induced dip. However, the speed and completeness of recovery can vary significantly. Some show a quick bounce back, while others indicate a more gradual return to previous levels, or even a sustained lower level if the shock led to permanent shifts.
*   **Pre-existing Trends:** It's crucial to observe the trends *before* and *after* the shaded periods. A shock might exacerbate a pre-existing decline or temporarily interrupt growth. The plots allow us to distinguish between a shock-induced anomaly and a longer-term trend.
*   **Vessel Type Specificity:** Different vessel types display distinct patterns:
    *   **Container Vessels:** Often exhibit relatively stable arrival patterns with a strong baseline. During 'Shock' periods, they typically show noticeable but often temporary drops (e.g., in Taipei, decreasing by -13.06%), though Kaohsiung's container traffic shows strong resilience with only minor changes. The recovery in green-shaded periods tends to be relatively quick, suggesting their essential role in global supply chains and strong underlying demand. However, severe or prolonged shocks can lead to more significant, lasting reductions, or strategic rerouting not immediately recovering to previous levels.
    *   **Passenger Vessels:** These are consistently among the most volatile. 'Shock' periods frequently coincide with dramatic and steep declines in arrivals (e.g., Keelung -48.28%, Hualien -42.86%), reflecting their high sensitivity to travel advisories, economic downturns affecting discretionary spending, and public health concerns. 'Recovery' periods can be inconsistent; some show a rapid rebound if the shock is brief, while others might indicate a slow or incomplete recovery if the underlying conditions (e.g., tourism demand) are durably altered.
    *   **Bulk & Dry Cargo:** The behavior of these vessels varies significantly by port. In ports where they are dominant (like Hualien), 'Shock' periods can lead to clear reductions (e.g., Bulk -15.82%, Dry Cargo -26.96%). In Keelung, Dry Cargo saw a -6.40% decline. Their 'Recovery' often ties closely to global commodity cycles and industrial demand, which may lag behind the immediate oil price recovery.
    *   **Tanker Vessels:** Tanker arrivals in Kaohsiung showed a positive change of 6.14% during oil shocks, suggesting either increased demand for oil transportation or strategic routing. During 'Shock' periods related to oil production or transport disruptions, their arrivals might decrease due to reduced supply or increase due to strategic stocking or rerouting. 'Recovery' patterns would depend on the stabilization of oil markets.
    *   **Other Vessels:** This heterogeneous category often exhibits the most extreme and varied responses. 'Shock' periods can lead to very sharp increases (e.g., Hualien +92.45%) or decreases (e.g., Keelung -27.90%, Taipei -16.48%), suggesting that this group includes highly flexible vessels or niche operations that are either particularly vulnerable or can capitalize on re-routing opportunities during disruptions. Their recovery is highly idiosyncratic and often reflects very specific market conditions for specialized services.

*   **Port-Specific Dynamics:** Each port's overall traffic volume and mix of vessel types influence how the shocks manifest:
    *   Major ports like Kaohsiung might show more muted reactions for their dominant vessel types due to their critical function in international trade.
    *   Smaller or specialized ports might exhibit more pronounced fluctuations or unique responses based on their niche markets.

**Key takeaway:** These individual time series plots offer valuable context to the aggregated percentage change figures. They allow for a visual assessment of the duration, magnitude, and recovery trajectory of arrival frequencies during periods of oil price volatility, providing insights into the dynamic resilience and vulnerability of different segments of port traffic.

### Detailed Analysis by Vessel Type: Lagged Effects and Specific Event Impact
 lagged correlations, the impact of specific geopolitical events, and comparisons with normal periods.
"""

shock_info = final_port_month_df[['port', 'year_month', 'oil_shock', 'event_name']].drop_duplicates()

# 1. Lagged Effects by Vessel Type
vt_lag_df = merged_vessel_type_shock_df.copy()
oil_data = final_port_month_df[['port', 'year_month', 'oil_change']].drop_duplicates()
vt_lag_df = pd.merge(vt_lag_df, oil_data, on=['port', 'year_month'], how='left')
vt_lag_df = vt_lag_df.sort_values(by=['port', 'vessel_type_group', 'year_month'])

for lag in range(1, 4):
    vt_lag_df[f'oil_change_lag_{lag}'] = vt_lag_df.groupby(['port', 'vessel_type_group'])['oil_change'].shift(lag)

vt_lagged_corrs = []
for vt in vt_lag_df['vessel_type_group'].unique():
    sub = vt_lag_df[vt_lag_df['vessel_type_group'] == vt]
    vt_lagged_corrs.append({
        'vessel_type': vt,
        'lag_0': sub['arrival_count'].corr(sub['oil_change']),
        'lag_1': sub['arrival_count'].corr(sub['oil_change_lag_1']),
        'lag_2': sub['arrival_count'].corr(sub['oil_change_lag_2']),
        'lag_3': sub['arrival_count'].corr(sub['oil_change_lag_3'])
    })

print("Vessel Type Arrivals vs Lagged Oil Changes (Correlations):")
display(pd.DataFrame(vt_lagged_corrs))

# 2. Impact of Specific Events by Vessel Type
event_vt_df = pd.merge(merged_vessel_type_shock_df, shock_info[['port', 'year_month', 'event_name']], on=['port', 'year_month'], how='left')
event_vt_summary = event_vt_df.dropna(subset=['event_name']).groupby(['event_name', 'vessel_type_group'])['arrival_count'].mean().unstack()

# 3. Non-Event Baseline
normal_vt_avg = event_vt_df[(event_vt_df['oil_shock'] == 0) & (event_vt_df['event_name'].isna())].groupby('vessel_type_group')['arrival_count'].mean().reset_index(name='avg_normal_arrivals')

# 4. Comparison Table
event_vt_melted = event_vt_summary.reset_index().melt(id_vars='event_name', var_name='vessel_type_group', value_name='avg_event_arrivals')
comparison_vt = pd.merge(event_vt_melted, normal_vt_avg, on='vessel_type_group', how='left')
comparison_vt['pct_change'] = ((comparison_vt['avg_event_arrivals'] - comparison_vt['avg_normal_arrivals']) / comparison_vt['avg_normal_arrivals']) * 100

print("\nPercentage Change: Specific Events vs Normal (By Vessel Type):")
display(comparison_vt.pivot(index='event_name', columns='vessel_type_group', values='pct_change').round(2))

# Visualization
plt.figure(figsize=(15, 8))
sns.barplot(x='event_name', y='pct_change', hue='vessel_type_group', data=comparison_vt)
plt.axhline(0, color='black', linewidth=1)
plt.title('Vessel Type Sensitivity: Impact of Specific Events vs Normal Periods', fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.ylabel('Percentage Change (%)')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""#### 1. Vessel Type Arrivals vs Lagged Oil Changes (Correlations)

This section showed the correlation coefficients between the `arrival_count` for each `vessel_type_group` and the `oil_change` at various lags (0, 1, 2, and 3 months).

*   **Overall Weak Correlations:** The correlations are generally very low, hovering close to zero for most vessel types across all lags. This indicates that, for the most part, there isn't a strong, direct linear relationship between a vessel type's arrival frequency and past oil price changes (up to 3 months prior).
*   **Slight Fluctuations:** While mostly weak, some vessel types show minor positive or negative correlations. For example, 'Bulk' vessels have a slightly positive correlation at lag 2 (`0.030833`), while 'Other' and 'Container' vessels generally show slight negative correlations. However, these are too small to suggest a significant predictive or explanatory power of lagged oil prices on arrival counts.
*   **No Clear Lagged Effect Pattern:** Unlike some economic indicators, there isn't a consistent pattern where a specific lag universally affects all vessel types, nor a clear trend of increasing or decreasing correlation with longer lags.

**Conclusion:** This analysis suggests that vessel arrivals, are either immediately responsive to oil price changes (which is captured by lag 0 and is also weak) or are influenced by a much more complex set of factors beyond simple lagged oil price movements that this linear correlation doesn't capture.

#### 2. Percentage Change: Specific Events vs Normal (By Vessel Type)

This table and the accompanying bar chart illustrate how the average monthly arrivals for each original vessel type change during specific geopolitical oil shock events compared to normal, non-event periods. This is a more direct and impactful measure of sensitivity.

*   **Widespread Negative Impacts:** Many events, such as the 'Abqaiq-Khurais Attack' and 'Hormuz Crisis', led to substantial decreases in arrivals for core vessel types like 'Bulk', 'Container', and 'Dry Cargo'. For instance, during the 'Hormuz Crisis', 'Bulk' vessels saw a **-33.80%** drop, and 'Dry Cargo' dropped by **-43.68%**.
*   **'Other' Vessel Type Volatility:** The 'Other' category often shows the most extreme percentage changes, both positive and negative. For example, it experienced a **-98.05%** drop during the 'US-Israel-Iran War' (indicating near cessation of traffic) and a **+88.40%** increase during 'Mid-East Escalation'. This suggests that this heterogeneous group is highly sensitive and reactive to geopolitical shifts.
*   **Container Vessels' Mixed Sensitivity:** 'Container' vessels often experience declines during major crises (e.g., 'Abqaiq-Khurais Attack': **-18.64%**), but interestingly, they show significant increases during other events like 'US-Iran Sanctions' (**+18.76%**). This could imply strategic rerouting or increased demand for specific trade lanes during these times.
*   **Passenger Vessels' Extreme Reactivity:** 'Passenger' vessels demonstrate high volatility, with a massive **+112.80%** increase during the 'Abqaiq-Khurais Attack' and a **-57.91%** drop during the 'Saudi-Russia Price War'. This highlights their immediate sensitivity to events that may affect travel advisories or tourism.
*   **Tankers' Moderate Declines:** 'Tanker' arrivals generally show declines during many events (e.g., 'Abqaiq-Khurais Attack': **-28.94%**), which is expected as oil infrastructure or shipping routes are directly impacted.

**Overall Insight:** While simple lagged oil price changes don't show strong correlations, specific geopolitical events have a very clear and often significant impact on different vessel types. The effects are not uniform; some vessel types and events lead to drastic declines, while others might even see increases due to re-routing or shifting demand dynamics.

### Unsupervised Learning Clustering Analysis

**Features:**
*   **`vessel_type_group` (船舶種類)**.
*   **`gross_tonnage` (噸位):** A proxy for DWT, indicating vessel size and potential energy consumption.
*   **`berth_wait_hours` (停留時長):** Represents the duration a vessel spends at berth.
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans
import numpy as np

df_clustering = all_inport_df.copy()

numerical_features = ['gross_tonnage', 'berth_wait_hours']
categorical_features = ['vessel_type_group']

# Numerical pipeline: impute missing values with the median, then scale
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Categorical pipeline: impute missing values with the most frequent, then one-hot encode
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a column transformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

X_processed = preprocessor.fit_transform(df_clustering)

# Get feature names after one-hot encoding
feature_names = numerical_features + list(preprocessor.named_transformers_['cat']['onehot'].get_feature_names_out(categorical_features))

# Convert the processed data back to a DataFrame
X_processed_df = pd.DataFrame(X_processed, columns=feature_names)

print("Shape of processed data:", X_processed.shape)
display(X_processed_df.head())

k = 4
kmeans_k4 = KMeans(n_clusters=k, random_state=42, n_init=10)
df_clustering['cluster'] = kmeans_k4.fit_predict(X_processed)

print(f"Number of vessels per cluster (k=4):\n{df_clustering['cluster'].value_counts()}")

print("\n--- Cluster Characteristics (k=4) ---")
display(df_clustering.groupby('cluster')[numerical_features].mean())

for cluster_id in sorted(df_clustering['cluster'].unique()):
    print(f"\nCluster {cluster_id} - Top Vessel Types:")
    display(df_clustering[df_clustering['cluster'] == cluster_id]['vessel_type_group'].value_counts(normalize=True).head(5))

print("\n--- Cluster Characteristics (Numerical Features) ---")
display(df_clustering.groupby('cluster')[numerical_features].mean())

print("\n--- Cluster Characteristics (Categorical Features) ---")
for cluster_id in sorted(df_clustering['cluster'].unique()):
    print(f"\nCluster {cluster_id} - Top Vessel Types:")
    display(df_clustering[df_clustering['cluster'] == cluster_id]['vessel_type_group'].value_counts(normalize=True).head(5))

"""### Cluster Characteristic Analysis & Interpretation

1.  **Cluster 0: Mixed Short-haul & Regional Fleet**
    *   **Features**: Average tonnage ~9,724 tons, short wait time (0.45 hours).
    *   **Composition**: Diverse mix including Dry Cargo (35%), Bulk (21%), and Tankers (20%). This group represents the most frequent daily port operations of small-to-mid-sized vessels.

2.  **Cluster 1: Long-haul Giant Container Vessels**
    *   **Features**: Highest average tonnage at **103,377 tons**, with slightly longer wait times (0.57 hours).
    *   **Composition**: Dominated by Container ships (81%). These are the massive international vessels. Theoretically, they should have the highest sensitivity to global oil price shocks due to high fuel consumption and long routes.

3.  **Cluster 2: High-Efficiency Regional Containers**
    *   **Features**: Average tonnage ~18,476 tons, the shortest wait time (0.37 hours).
    *   **Composition**: Nearly 100% Container ships. This group represents regional feeder fleets or hub-to-hub ships optimized for rapid turnaround.

4.  **Cluster 3: Extreme Operational Outliers**
    *   **Features**: Moderate tonnage (3,301 tons) but extreme wait times averaging 249 hours (10 days).
    *   **Composition**: The 7 specific anomalous vessels identified previously.

### Cluster Structure Analysis Per Port
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Map Chinese port names to English
port_map_en = {
    '臺北港': 'Taipei',
    '花蓮港': 'Hualien',
    '高雄港': 'Kaohsiung',
    '基隆港': 'Keelung'
}

# 1. Create a crosstab of Ports vs Clusters
port_cluster_dist = pd.crosstab(df_clustering['port'], df_clustering['cluster'])
port_cluster_dist.index = port_cluster_dist.index.map(port_map_en)

# 2. Normalize by row to get percentages
port_cluster_pct = port_cluster_dist.div(port_cluster_dist.sum(axis=1), axis=0) * 100

print("Vessel Count per Cluster by Port:")
display(port_cluster_dist)

"""### Oil Shock Sensitivity Analysis
evaluate how the arrivals of each of the 4 clusters change during months marked as `oil_shock == 1`.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Prepare monthly cluster counts from the global clustering results
cluster_monthly = df_clustering.groupby(['port', 'year_month', 'cluster']).size().reset_index(name='arrival_count')

# 2. Merge with oil shock indicators from final_port_month_df
final_port_month_df['year_month'] = final_port_month_df['year_month'].astype(str)
shock_info = final_port_month_df[['port', 'year_month', 'oil_shock', 'event_name']].drop_duplicates()

merged_shock_df = pd.merge(
    cluster_monthly,
    shock_info,
    on=['port', 'year_month'],
    how='left'
)

# 3. Calculate average arrivals per cluster during Shock vs. Non-Shock
# Note: We filter out Cluster 3 as it only has 7 total vessels and isn't statistically significant for trends
analysis_df = merged_shock_df[merged_shock_df['cluster'] != 3]
shock_stats = analysis_df.groupby(['cluster', 'oil_shock'])['arrival_count'].mean().unstack()

# 4. Calculate Percentage Change
# (Mean_Shock - Mean_NoShock) / Mean_NoShock * 100
shock_stats['pct_change'] = ((shock_stats[1] - shock_stats[0]) / shock_stats[0]) * 100

print("Sensitivity Analysis: Arrival Changes during Oil Shocks")
display(shock_stats)

"""### 敏感度分析：分港口與分群之油價衝擊影響 (Per Port & Cluster Sensitivity)

分析不同港口在油價衝擊期間，各分群到港量的百分比變動。
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. 計算分港口、分群、油價衝擊狀態的平均到港量
port_shock_stats = analysis_df.groupby(['port', 'cluster', 'oil_shock'])['arrival_count'].mean().unstack()

# 2. 計算百分比變動
port_shock_stats['pct_change'] = ((port_shock_stats[1] - port_shock_stats[0]) / port_shock_stats[0]) * 100

# 3. 整理成易於閱讀與繪圖的格式
port_shock_results = port_shock_stats.reset_index()
port_shock_results['port_en'] = port_shock_results['port'].map(port_map_en)

print("分港口各分群之油價敏感度數據：")
display(port_shock_results[['port_en', 'cluster', 'pct_change']])

# 4. 視覺化比較
plt.figure(figsize=(10, 6))
sns.barplot(x='port_en', y='pct_change', hue='cluster', data=port_shock_results, palette='viridis')
plt.axhline(0, color='black', linewidth=1)
plt.title('Percentage Change in Arrivals During Oil Shocks: By Port and Cluster', fontsize=14)
plt.ylabel('Change in Arrivals (%)')
plt.xlabel('Port')
plt.legend(title='Cluster ID', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""**Hualien Port's Resilience Paradox:**
While most clusters saw a decline, Cluster 1 at Hualien showed a massive increase. However, since Cluster 1 represents giant vessels and Hualien is a smaller specialized port, this might be due to a very low baseline of such arrivals.

**Taipei and Keelung Vulnerability:**
Both ports show double-digit drops in Cluster 0 (Short-haul) arrivals, suggesting that smaller, frequent regional trips are the first to be consolidated or cancelled during price shocks.

**Kaohsiung's Stability:**
As the major global hub, Kaohsiung exhibits the most stability, with only minor percentage drops across all clusters, reinforcing its status as a critical, non-discretionary node in international shipping.

### Cluster 3: 異常營運分析 (Extreme Operational Outliers)

在本次分群中，**Cluster 3** 是一個極其特殊的群組，僅包含 **7 艘船舶**。以下是該群組的關鍵特性分析：

*   **極端停泊時長**：平均等候時間高達 **249 小時 (約 10 天)**，遠超其他群組的 0.4-0.6 小時。這類船舶可能涉及維修、法律糾紛、長期檢疫或特殊的物資轉運流程。
*   **統計處理說明**：由於樣本數過少（僅佔總資料量的 0.003%），在進行「油價衝擊敏感度」等趨勢分析時，將其納入計算會導致百分比變動極度不穩定且不具代表性（例如：一艘船的增減即代表 14% 的波動）。
*   **報告建議**：
    *   將 Cluster 3 定義為「**營運異常監測組**」。
    *   在敏感度模型中將其排除，以確保大數據分析的統計穩健性（Robustness）。
    *   建議港口管理方針對此類極端個案建立獨立的追蹤機制，因為其對特定泊位的佔用時間極長，雖不影響整體油價敏感度趨勢，但對局部泊位週轉率有顯著影響。

### Lagged Effects of Oil Price Changes （這個的結論是沒啥關係 但還是留給你們看）

calculate the correlations between `oil_change` and `arrival_count` for each cluster, incorporating lags of 1, 2, and 3 months to see if market reactions are delayed.
"""

import pandas as pd

# 1. Prepare monthly data with oil price changes
# We use the 'merged_shock_df' created in the sensitivity analysis step
lag_analysis_df = merged_shock_df.copy()

# Sort to ensure shift() works correctly
lag_analysis_df = lag_analysis_df.sort_values(by=['port', 'cluster', 'year_month'])

# 2. Re-merge with oil_change from final_port_month_df
oil_data = final_port_month_df[['port', 'year_month', 'oil_change']].drop_duplicates()
lag_analysis_df = pd.merge(lag_analysis_df, oil_data, on=['port', 'year_month'], how='left')

# 3. Create lagged features
for lag in range(1, 4):
    lag_analysis_df[f'oil_change_lag_{lag}'] = lag_analysis_df.groupby(['port', 'cluster'])['oil_change'].shift(lag)

# 4. Calculate Correlations
lagged_correlations = []
for cluster_id in sorted(lag_analysis_df['cluster'].unique()):
    cluster_subset = lag_analysis_df[lag_analysis_df['cluster'] == cluster_id]

    corrs = {
        'cluster': cluster_id,
        'corr_lag_0': cluster_subset['arrival_count'].corr(cluster_subset['oil_change']),
        'corr_lag_1': cluster_subset['arrival_count'].corr(cluster_subset['oil_change_lag_1']),
        'corr_lag_2': cluster_subset['arrival_count'].corr(cluster_subset['oil_change_lag_2']),
        'corr_lag_3': cluster_subset['arrival_count'].corr(cluster_subset['oil_change_lag_3'])
    }
    lagged_correlations.append(corrs)

corr_results_df = pd.DataFrame(lagged_correlations)
print("Correlations between Arrival Counts and Lagged Oil Price Changes:")
display(corr_results_df)

# 5. Visualization
corr_results_df.set_index('cluster').plot(kind='bar', figsize=(12, 6))
plt.title('Correlation of Arrivals with Lagged Oil Price Changes by Cluster')
plt.ylabel('Correlation Coefficient')
plt.axhline(0, color='black', linewidth=0.8)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.legend(title='Lag (Months)')
plt.show()

"""### Analyzing Impact of Specific Oil Shock Events

Analyze the average arrivals per cluster during specific historical events identified in the data.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Filter for periods with specific named events
# merged_shock_df was created in previous steps and contains event_name
specific_events_df = merged_shock_df.dropna(subset=['event_name']).copy()

if not specific_events_df.empty:
    # 2. Group by event and cluster to find average arrivals
    # We filter out cluster 3 for visualization consistency as established earlier
    event_impact = specific_events_df[specific_events_df['cluster'] != 3].groupby(['event_name', 'cluster'])['arrival_count'].mean().unstack()

    print("Average Cluster Arrivals during Specific Oil Shock Events:")
    display(event_impact)

    # 3. Visualization
    ax = event_impact.plot(kind='bar', figsize=(14, 7), width=0.8)
    plt.title('Impact of Specific Geopolitical Events on Cluster Arrivals', fontsize=14)
    plt.ylabel('Average Monthly Arrivals')
    plt.xlabel('Disruption Event')
    plt.xticks(rotation=45, ha='right')
    plt.legend(title='Cluster ID')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.show()

"""### Average Cluster Arrivals During 'Non-Event' Periods

 the average monthly arrivals for each cluster during periods where no oil shock (`oil_shock == 0`) and no specific `event_name` was recorded. This represents the 'normal' operational state.
"""

non_event_arrivals = merged_shock_df[(merged_shock_df['oil_shock'] == 0) & (merged_shock_df['event_name'].isna())]

# Filter out Cluster 3 for consistency with previous analysis if it was filtered there
non_event_arrivals_filtered = non_event_arrivals[non_event_arrivals['cluster'] != 3]

# Calculate average arrivals for each cluster during non-event periods
avg_non_event_cluster_arrivals = non_event_arrivals_filtered.groupby('cluster')['arrival_count'].mean().reset_index()
avg_non_event_cluster_arrivals.rename(columns={'arrival_count': 'avg_non_event_arrivals'}, inplace=True)

print("Average Cluster Arrivals during 'Non-Event' Periods:")
display(avg_non_event_cluster_arrivals)

"""### Comparison: Average Cluster Arrivals (Non-Event vs. Specific Oil Shocks)

Put the 'non-event' averages alongside the 'specific event' averages and calculate the percentage change to see the impact .
"""

# Reset index of event_impact to make 'cluster' a column for merging
event_impact_reset = event_impact.reset_index()

# Prepare event_impact for merging: melt to have event_name and value, then pivot to have events as columns
event_impact_melted = event_impact_reset.melt(id_vars=['event_name'], var_name='cluster', value_name='avg_event_arrivals')

# Merge non_event_arrivals with event_impact_melted
comparison_df = pd.merge(
    event_impact_melted,
    avg_non_event_cluster_arrivals,
    on='cluster',
    how='left'
)

# Calculate percentage change
comparison_df['pct_change_from_non_event'] = ((comparison_df['avg_event_arrivals'] - comparison_df['avg_non_event_arrivals']) / comparison_df['avg_non_event_arrivals']) * 100

print("Comparison of Average Cluster Arrivals (Non-Event vs. Specific Events) and Percentage Change:")
display(comparison_df.sort_values(by=['cluster', 'event_name']))

# Optionally, visualize the comparison for a specific cluster or overall
plt.figure(figsize=(15, 8))
sns.barplot(x='event_name', y='pct_change_from_non_event', hue='cluster', data=comparison_df)
plt.axhline(0, color='black', linewidth=0.8)
plt.title('Percentage Change in Cluster Arrivals During Specific Events vs. Non-Event Periods')
plt.xlabel('Specific Oil Shock Event')
plt.ylabel('Percentage Change in Arrivals (%)')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Cluster ID')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Final Insights and Recommendations

1.  **Cluster-Specific Vulnerability**: The analysis clearly shows that different vessel clusters respond differently to oil price shocks. Short-haul and regional vessels (Cluster 0) and container vessels (Cluster 1, 2) are particularly sensitive, often showing double-digit declines in arrivals during shock periods. This suggests that these segments are the first to adjust their schedules or consolidate trips.

2.  **Port-Specific Resilience**: Major global hubs like Kaohsiung exhibit remarkable stability during oil price shocks, indicating their critical role in international trade that cannot be easily substituted. Smaller, more specialized ports like Hualien show more volatile responses, sometimes with unexpected increases in specific clusters, which warrants further investigation into their operational nuances.

3.  **No Clear Lagged Effect**: The correlation analysis between lagged oil price changes and vessel arrivals does not show a strong, consistent relationship. This suggests that market reactions to oil price fluctuations are either immediate or influenced by a complex interplay of factors beyond simple lagged price changes.

4.  **Anomaly Detection (Cluster 3)**: The identification of Cluster 3 as 'Extreme Operational Outliers' highlights the importance of robust data preprocessing and clustering. While these vessels do not represent a significant trend for economic analysis due to their low count, they are crucial for operational monitoring and management, potentially indicating issues like maintenance, legal hold-ups, or specific logistical challenges.

5.  **Quantified Impact of Specific Oil Shock Events**: The comparison of average cluster arrivals during 'non-event' periods versus 'specific oil shock events' reveals the direct impact of these events:
    *   **Cluster 0 (Mixed Short-haul & Regional Fleet)**: Generally experiences significant negative impacts during most events (e.g., Hormuz Crisis: -36.48% drop). However, some events like 'US-Iran Sanctions' show an increase (+10.18%), suggesting a complex re-routing or demand shift.
    *   **Cluster 1 (Long-haul Giant Container Vessels)**: Also vulnerable, with significant declines during events like 'Israel-Hamas War' (-25.10%) and 'Hormuz Crisis' (-18.61%). Interestingly, 'US-Iran Sanctions' leads to a substantial increase (+38.54%), indicating potential strategic redirection or increased demand for these large vessels in certain scenarios.
    *   **Cluster 2 (High-Efficiency Regional Containers)**: Shows mixed, often negative, responses, such as drops during 'Hormuz Crisis' (-21.82%). Similar to other clusters, some events like 'US-Iran Sanctions' and 'US-Iran Tension' correlate with increased arrivals.
    *   **Extreme Disruptions**: Events like 'US-Israel-Iran War' caused near-complete cessation of arrivals for Cluster 0 (-99.64%), highlighting severe, potentially localized, disruptions.

6.  **Strategic Implications for Port Management**: To mitigate the impact of oil price volatility, ports could consider:
    *   **Incentivizing Resilient Clusters**: Offer preferential services or reduced fees for vessel types (e.g., larger, more stable container vessels) that show less sensitivity to shocks.
    *   **Targeted Support for Vulnerable Clusters**: Implement support measures for short-haul or regional vessels during periods of high oil prices, such as optimizing turnaround times or providing fuel-efficiency guidance.
    *   **Enhanced Anomaly Monitoring**: Develop dedicated systems to track and manage vessels identified as operational outliers (Cluster 3) to minimize their impact on berth utilization and overall port efficiency.

### Final Insights and Recommendations

1.  **Cluster-Specific Vulnerability**: The analysis clearly shows that different vessel clusters respond differently to oil price shocks. Short-haul and regional vessels (Cluster 0) and container vessels (Cluster 1, 2) are particularly sensitive, often showing double-digit declines in arrivals during shock periods. This suggests that these segments are the first to adjust their schedules or consolidate trips.

2.  **Port-Specific Resilience**: Major global hubs like Kaohsiung exhibit remarkable stability during oil price shocks, indicating their critical role in international trade that cannot be easily substituted. Smaller, more specialized ports like Hualien show more volatile responses, sometimes with unexpected increases in specific clusters, which warrants further investigation into their operational nuances.

3.  **No Clear Lagged Effect**: The correlation analysis between lagged oil price changes and vessel arrivals does not show a strong, consistent relationship. This suggests that market reactions to oil price fluctuations are either immediate or influenced by a complex interplay of factors beyond simple lagged price changes.

4.  **Anomaly Detection (Cluster 3)**: The identification of Cluster 3 as 'Extreme Operational Outliers' highlights the importance of robust data preprocessing and clustering. While these vessels do not represent a significant trend for economic analysis due to their low count, they are crucial for operational monitoring and management, potentially indicating issues like maintenance, legal hold-ups, or specific logistical challenges.

5.  **Quantified Impact of Specific Oil Shock Events**: The comparison of average cluster arrivals during 'non-event' periods versus 'specific oil shock events' reveals the direct impact of these events:
    *   **Cluster 0 (Mixed Short-haul & Regional Fleet)**: Generally experiences significant negative impacts during most events (e.g., Hormuz Crisis: -36.48% drop). However, some events like 'US-Iran Sanctions' show an increase (+10.18%), suggesting a complex re-routing or demand shift.
    *   **Cluster 1 (Long-haul Giant Container Vessels)**: Also vulnerable, with significant declines during events like 'Israel-Hamas War' (-25.10%) and 'Hormuz Crisis' (-18.61%). Interestingly, 'US-Iran Sanctions' leads to a substantial increase (+38.54%), indicating potential strategic redirection or increased demand for these large vessels in certain scenarios.
    *   **Cluster 2 (High-Efficiency Regional Containers)**: Shows mixed, often negative, responses, such as drops during 'Hormuz Crisis' (-21.82%). Similar to other clusters, some events like 'US-Iran Sanctions' and 'US-Iran Tension' correlate with increased arrivals.
    *   **Extreme Disruptions**: Events like 'US-Israel-Iran War' caused near-complete cessation of arrivals for Cluster 0 (-99.64%), because there was only 1 boat anyway

6.  **Strategic Implications for Port Management**: To mitigate the impact of oil price volatility, ports could consider:
    *   **Incentivizing Resilient Clusters**: Offer preferential services or reduced fees for vessel types (e.g., larger, more stable container vessels) that show less sensitivity to shocks.
    *   **Targeted Support for Vulnerable Clusters**: Implement support measures for short-haul or regional vessels during periods of high oil prices, such as optimizing turnaround times or providing fuel-efficiency guidance.
    *   **Enhanced Anomaly Monitoring**: Develop dedicated systems to track and manage vessels identified as operational outliers (Cluster 3) to minimize their impact on berth utilization and overall port efficiency.
"""

import statsmodels.api as sm
import statsmodels.formula.api as smf

"""## TEU DIAGNOSTIC ANALYSIS"""

import pandas as pd
import numpy as np
import statsmodels.formula.api as smf

print("================ WORK 1: TEU ANALYSIS (CHINESE ALIGN) ================")

# 1. 讀取資料
teu_raw = pd.read_csv('/content/drive/MyDrive/BigData Final Poject/data/臺灣國際商港貨櫃裝卸量.csv')

# 2. 自動偵測欄位
port_col = [col for col in teu_raw.columns if '港' in col or 'port' in col.lower()][0]
time_col = [col for col in teu_raw.columns if '年' in col or '月' in col or 'date' in col.lower() or 'time' in col.lower()][0]
teu_col = [col for col in teu_raw.columns if any(k in col.lower() for k in ['總計', '合計', 'teu', 'total', '裝卸量'])][0]

teu_cleaned = teu_raw[[port_col, time_col, teu_col]].copy()
teu_cleaned.columns = ['port', 'year_month', 'teu']

# 3. 修正：對齊成與油價主表一樣的「中文港口名稱」
port_code_to_zh = {
    'TWKEL': '基隆港',
    'TWTPE': '臺北港',
    'TWKHH': '高雄港',
    'TWTXG': '臺中港'
}
teu_cleaned['port'] = teu_cleaned['port'].astype(str).str.strip().map(port_code_to_zh)
teu_cleaned = teu_cleaned.dropna(subset=['port'])

# 4. 時間格式清洗 (對齊為 YYYY-MM)
teu_cleaned['year_month'] = teu_cleaned['year_month'].astype(str).str.replace('/', '-')
def convert_to_west_year(val):
    try:
        parts = val.split('-')
        if len(parts[0]) <= 3: # 民國年
            parts[0] = str(int(parts[0]) + 1911)
        return f"{parts[0]}-{str(parts[1]).zfill(2)}"
    except:
        return val

teu_cleaned['year_month'] = teu_cleaned['year_month'].apply(convert_to_west_year)

# 5. 清理 TEU 數值（去掉千分位逗號）
teu_cleaned['teu'] = pd.to_numeric(teu_cleaned['teu'].astype(str).str.replace(',', ''), errors='coerce')
teu_cleaned = teu_cleaned.dropna(subset=['teu'])

# 6. 讀取並重塑油價主表
final_df = final_port_month_df.copy()

# 確保兩邊的字串都沒有隱藏的空格
teu_cleaned['port'] = teu_cleaned['port'].astype(str).str.strip()
final_df['port'] = final_df['port'].astype(str).str.strip()

teu_cleaned['year_month'] = teu_cleaned['year_month'].astype(str).str.strip()
final_df['year_month'] = final_df['year_month'].astype(str).str.strip()

# 7. 合併資料
model_teu_df = pd.merge(
    teu_cleaned,
    final_df[['port', 'year_month', 'oil_change', 'oil_change_pct', 'oil_shock']],
    on=['port', 'year_month'],
    how='inner'
)

print(f" 中文字串對齊成功 合併完成後的資料筆數為 {len(model_teu_df)} 筆。")

if len(model_teu_df) == 0:
    print(" 錯誤：中文字串一樣卻合不起來，檢查時間格式")
else:
    # 8. 排序、建立滯後項、排除空值
    model_teu_df = model_teu_df.sort_values(by=['port', 'year_month'])
    model_teu_df['teu_lag_1'] = model_teu_df.groupby(['port'])['teu'].shift(1)
    model_teu_df = model_teu_df.dropna(subset=['teu_lag_1', 'oil_change', 'oil_shock'])

    # 9. 執行迴歸模型 (因為 Statsmodels 處理中文變數名稱有時會敏感，C(port) 確保類別型態正確)
    model_teu = smf.ols(
        'teu ~ teu_lag_1 + oil_change + oil_change_pct + oil_shock + C(port)',
        data=model_teu_df
    ).fit()

    print("\n [工作一] TEU 時間序列分析：")
    print(model_teu.summary())

"""## VESSEL CLUSTER ANALYSIS"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf

print("================ WORK 2: VESSEL CLUSTER ANALYSIS ================")

# 1. 確保基礎資料結構正確，並過濾掉異常值 Cluster 3
reg_df = lag_analysis_df.copy()
reg_df.columns = reg_df.columns.str.lower()
reg_df = reg_df[reg_df['cluster'] != 3]

# 2. 強制將港口名稱英文化或中文字串去空格，確保跟前方的 lag_analysis_df 結構完全對齊
reg_df['port'] = reg_df['port'].astype(str).str.strip()

# 3. 重新排序並建立油價變動的滯後變數
reg_df = reg_df.sort_values(by=['port', 'cluster', 'year_month'])
for lag in range(1, 4):
    reg_df[f'oil_change_lag_{lag}'] = reg_df.groupby(['port', 'cluster'])['oil_change'].shift(lag)

# 4. 建立到港量本身的自相關滯後項（解決像 Durbin-Watson 序列相關等細節）
reg_df['arrival_count_lag_1'] = reg_df.groupby(['port', 'cluster'])['arrival_count'].shift(1)

# 5. 迴圈跑完三個群組
clusters_to_run = [0, 1, 2]
cluster_names = {
    0: "Cluster 0 (混合型近岸/區域短程船隊)",
    1: "Cluster 1 (遠洋巨型貨櫃輪)",
    2: "Cluster 2 (高效率區域/近海貨櫃船)"
}

for c_id in clusters_to_run:
    print(f"\n" + "="*70)
    print(f" 正在估計模型：{cluster_names[c_id]}")
    print(f"="*70)

    # 篩選特定分群並剔除缺失值
    sub_df = reg_df[reg_df['cluster'] == c_id].dropna(
        subset=['arrival_count', 'arrival_count_lag_1', 'oil_change', 'oil_change_lag_1', 'oil_change_lag_2', 'oil_shock']
    )

    # 執行包含自相關控制的時間序列面板固定效應迴歸模型
    # C(port) 控制四大港口的規模基準線差異
    model = smf.ols(
        'arrival_count ~ arrival_count_lag_1 + oil_change + oil_change_lag_1 + oil_change_lag_2 + oil_shock + C(port)',
        data=sub_df
    ).fit()

    # 列印整體模型指標
    print(f" 模型解釋力 R-squared: {model.rsquared:.4f}  (Adj. R-squared: {model.rsquared_adj:.4f})")

    # 計算殘差的 Durbin-Watson 統計量
    dw_stat = sm.stats.stattools.durbin_watson(model.resid)
    print(f" 殘差自相關 Durbin-Watson 指標: {dw_stat:.3f} (接近 2 代表完全無序列相關，模型穩健)")
    print("\n 主要變數估計結果（看 Coef 和 P>|t|）：")

    # 擷取變數大表
    print(model.summary().tables[1])

# --- TEU BEFORE / AFTER IMPACT CHARTS (ENGLISH PORT NAMES) ---

import pandas as pd
import matplotlib.pyplot as plt

# Mapping from Chinese to English
port_map_en = {
    '基隆港': 'Keelung',
    '臺北港': 'Taipei',
    '高雄港': 'Kaohsiung',
    '臺中港': 'Taichung',
    '花蓮港': 'Hualien'
}

teu_plot_df = model_teu_df.copy()
teu_plot_df['date'] = pd.to_datetime(teu_plot_df['year_month'])

shock_info = final_port_month_df[['port', 'year_month', 'oil_shock']].drop_duplicates()
shock_info['date'] = pd.to_datetime(shock_info['year_month'])

teu_plot_df = pd.merge(
    teu_plot_df.drop(columns=['oil_shock'], errors='ignore'),
    shock_info[['port', 'date', 'oil_shock']],
    on=['port', 'date'],
    how='left'
)

N_RECOVERY = 3

def label_recovery(group, n_recovery=N_RECOVERY):
    group = group.sort_values('date').copy()
    group['regime'] = 'Normal'
    group.loc[group['oil_shock'] == 1, 'regime'] = 'Shock'

    shock_mask = group['oil_shock'] == 1
    starts = group.index[shock_mask & (~shock_mask.shift(1, fill_value=False))]

    for start_idx in starts:
        idx_pos = group.index.get_loc(start_idx)
        end_pos = idx_pos
        while end_pos + 1 < len(group) and group['oil_shock'].iloc[end_pos + 1] == 1:
            end_pos += 1
        for k in range(1, n_recovery + 1):
            pos = end_pos + k
            if pos >= len(group):
                break
            if group['regime'].iloc[pos] == 'Normal':
                group.iloc[pos, group.columns.get_loc('regime')] = 'Recovery'
    return group

teu_plot_df = teu_plot_df.groupby('port', group_keys=False).apply(label_recovery)

ports_to_plot = teu_plot_df['port'].unique()

for p in ports_to_plot:
    sub = teu_plot_df[teu_plot_df['port'] == p].sort_values('date')

    # Use English name for the title (fallback to original if not in dict)
    port_en = port_map_en.get(p, str(p))

    fig, ax = plt.subplots(figsize=(12, 5))

    ax.plot(sub['date'], sub['teu'], color='black', linewidth=1.5, label='TEU')

    for regime, color, alpha in [('Shock', 'red', 0.18), ('Recovery', 'green', 0.12)]:
        mask = sub['regime'] == regime
        if not mask.any():
            continue
        group_id = (mask.ne(mask.shift(fill_value=False))).cumsum()
        for gid, gsub in sub[mask].groupby(group_id):
            ax.axvspan(
                gsub['date'].min(),
                gsub['date'].max(),
                color=color,
                alpha=alpha,
                label=regime if regime not in ax.get_legend_handles_labels()[1] else None
            )

    ax.set_title(f'TEU Time Series with Oil Shock / Recovery - {port_en}')
    ax.set_xlabel('Date')
    ax.set_ylabel('TEU')
    ax.grid(True, linestyle='--', alpha=0.4)

    handles, labels = ax.get_legend_handles_labels()
    seen = set()
    new_h, new_l = [], []
    for h, l in zip(handles, labels):
        if l not in seen:
            seen.add(l)
            new_h.append(h)
            new_l.append(l)
    ax.legend(new_h, new_l)

    plt.tight_layout()
    plt.show()

# --- VESSEL ARRIVAL FREQUENCY BEFORE / AFTER IMPACT CHARTS ---

import pandas as pd
import matplotlib.pyplot as plt

# Start from cluster_monthly (port, year_month, cluster, arrival_count)
cluster_plot_df = cluster_monthly.copy()
cluster_plot_df['date'] = pd.to_datetime(cluster_plot_df['year_month'])

# Add oil_shock info
shock_info = final_port_month_df[['port', 'year_month', 'oil_shock']].drop_duplicates()
shock_info['date'] = pd.to_datetime(shock_info['year_month'])

cluster_plot_df = pd.merge(
    cluster_plot_df,
    shock_info[['port', 'date', 'oil_shock']],
    on=['port', 'date'],
    how='left'
)

# Reuse the same regime labelling function as above
def label_recovery(group, n_recovery=N_RECOVERY):
    group = group.sort_values('date').copy()
    group['regime'] = 'Normal'
    group.loc[group['oil_shock'] == 1, 'regime'] = 'Shock'
    shock_mask = group['oil_shock'] == 1
    starts = group.index[shock_mask & (~shock_mask.shift(1, fill_value=False))]
    for start_idx in starts:
        idx_pos = group.index.get_loc(start_idx)
        end_pos = idx_pos
        while end_pos + 1 < len(group) and group['oil_shock'].iloc[end_pos + 1] == 1:
            end_pos += 1
        for k in range(1, n_recovery + 1):
            pos = end_pos + k
            if pos >= len(group):
                break
            if group['regime'].iloc[pos] == 'Normal':
                group.iloc[pos, group.columns.get_loc('regime')] = 'Recovery'
    return group

cluster_plot_df = cluster_plot_df.groupby(['port', 'cluster'], group_keys=False).apply(label_recovery)

# ------------- Plot (separate figure per port x cluster) -------------

for p in sorted(cluster_plot_df['port'].unique()):
    for c in sorted(cluster_plot_df['cluster'].unique()):
        sub = cluster_plot_df[(cluster_plot_df['port'] == p) &
                              (cluster_plot_df['cluster'] == c)].sort_values('date')
        if sub.empty:
            continue

        fig, ax = plt.subplots(figsize=(12, 4))

        # main arrival count line
        ax.plot(sub['date'], sub['arrival_count'],
                color='navy', linewidth=1.4, label='Arrivals')

        # shaded regimes
        for regime, color, alpha in [('Shock', 'red', 0.18), ('Recovery', 'green', 0.12)]:
            mask = sub['regime'] == regime
            if not mask.any():
                continue
            group_id = (mask.ne(mask.shift(fill_value=False))).cumsum()
            for gid, gsub in sub[mask].groupby(group_id):
                ax.axvspan(gsub['date'].min(), gsub['date'].max(),
                           color=color, alpha=alpha, label=regime if gid == gsub.index[0] else None)

        port_en = port_map_en.get(p, str(p))
        ax.set_title(f'Cluster {c} Arrivals with Shock / Recovery - {port_en}')

        ax.set_xlabel('Date')
        ax.set_ylabel('Arrival Count')
        ax.grid(True, linestyle='--', alpha=0.4)

        handles, labels = ax.get_legend_handles_labels()
        seen = {}
        new_h, new_l = [], []
        for h, l in zip(handles, labels):
            if l not in seen:
                seen[l] = True
                new_h.append(h)
                new_l.append(l)
        ax.legend(new_h, new_l)

        plt.tight_layout()
        plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("===== ESG CORRELATION HEATMAP: OIL VS. IDLING / EMISSIONS PROXY =====")

# 1. Make sure year_month is aligned as string
all_inport_df['year_month'] = all_inport_df['year_month'].astype(str).str.strip()
final_port_month_df['year_month'] = final_port_month_df['year_month'].astype(str).str.strip()

# 2. Build an emissions / idling proxy at vessel level
#    Simple proxy: gross_tonnage * berth_wait_hours
all_inport_df['co2_proxy'] = (
    all_inport_df['gross_tonnage'].fillna(0) *
    all_inport_df['berth_wait_hours'].fillna(0)
)

# 3. Aggregate to (port, year_month) level
esg_monthly = (
    all_inport_df
    .groupby(['port', 'year_month'], as_index=False)
    .agg(
        total_co2_proxy=('co2_proxy', 'sum'),        # total emissions proxy
        avg_co2_proxy=('co2_proxy', 'mean'),         # average per vessel
        avg_berth_wait=('berth_wait_hours', 'mean'), # idling time proxy
        total_vessels=('co2_proxy', 'size')          # traffic volume
    )
)

# 4. Merge with monthly oil data
#    (oil_price, oil_change, oil_change_pct, oil_shock, etc. already in final_port_month_df)
oil_cols = ['oil_price', 'oil_change', 'oil_change_pct', 'oil_shock']
oil_cols = [c for c in oil_cols if c in final_port_month_df.columns]

esg_merged = pd.merge(
    esg_monthly,
    final_port_month_df[['port', 'year_month'] + oil_cols],
    on=['port', 'year_month'],
    how='inner'
)

print(f"Merged ESG dataset rows: {len(esg_merged)}")
display(esg_merged.head())

# 5. (Optional) Focus on one port if you want a cleaner signal, e.g., Kaohsiung
#    Comment this out if you want all ports combined.
# esg_merged = esg_merged[esg_merged['port'] == '高雄港'].copy()

# 6. Select variables for correlation
corr_vars = [
    'oil_price',        # absolute oil level
    'oil_change',       # month-on-month change
    'oil_change_pct',   # % change
    'total_co2_proxy',  # total emissions proxy
    'avg_co2_proxy',    # per-vessel emissions proxy
    'avg_berth_wait',   # idling time
    'total_vessels'     # traffic
]
corr_vars = [c for c in corr_vars if c in esg_merged.columns]

corr_df = esg_merged[corr_vars]

# 7. Compute correlation matrix
corr_matrix = corr_df.corr()

print("Correlation matrix between oil metrics and ESG proxies:")
display(corr_matrix)

# 8. Plot ESG correlation heatmap
plt.figure(figsize=(10, 7))
sns.heatmap(
    corr_matrix,
    annot=True,
    fmt=".2f",
    cmap='RdBu_r',
    center=0,
    linewidths=0.5,
    cbar_kws={'label': 'Correlation'}
)
plt.title('ESG Correlation Heatmap: Oil vs. Idling / Emissions Proxies')
plt.yticks(rotation=0)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()



"""**Final Report: Impact of Oil Shocks on Port Operations and Vessel Dynamics**

**Executive Summary**
This analysis explores the resilience and vulnerability of port operations and vessel traffic in Taiwan's major international ports (Keelung, Taipei, Hualien, Kaohsiung) to oil price shocks and geopolitical events. Using a combination of descriptive statistics, clustering analysis, time-series visualizations, and regression models, we identify distinct patterns of response across different ports and vessel types. Key findings indicate significant variations in sensitivity, the importance of port specialization, and a nuanced relationship between oil prices and port-related emissions.

**1. Vessel Type Composition by Port**

Ports exhibit clear specializations:

**Keelung & Kaohsiung:** Predominantly handle Container vessels (approx. 53.8% and 49.9% respectively), signifying their roles as major container hubs.

**Taipei:** Shows a diverse composition, with significant Container (41.6%), 'Other' (21.5%), and Dry Cargo (17.5%) traffic, indicating a broader range of activities.

**Hualien:** Heavily dominated by Bulk (40.7%) and Dry Cargo (28.6%) vessels, with virtually no Container traffic, highlighting its focus on commodity movements.

**2. Overall Port Sensitivity to Oil Shocks**
High-level analysis of average monthly arrivals during oil shock periods reveals varying vulnerabilities:

**Hualien Port:** Most sensitive, experiencing a -14.26% drop in average monthly arrivals during shocks.

**Taipei Port: **Also significantly affected, with a -9.16% decrease.
Keelung Port: Shows a moderate decline of -5.86%.

**Kaohsiung Port:** The most resilient, with only a -2.99% drop, reinforcing its status as a critical global gateway.

**3. Sensitivity Analysis by Port and Vessel Type**
Detailed examination shows that impact varies by vessel type within each port:

**Keelung Port:** Dry Cargo (-6.4%) and Passenger (-48.3%) vessels are highly vulnerable. Bulk vessels surprisingly show a slight increase (+2.3%), while Container traffic sees a minor decrease (-0.85%).

**Taipei Port:** Experiences broad declines across major vessel types (Bulk: -17.9%, Dry Cargo: -16.9%, Container: -13.1%).

**Hualien Port:** Bulk (-15.8%) and Dry Cargo (-27.0%) are negatively impacted. Passenger traffic also drops significantly (-42.9%), but 'Other' vessels show a substantial increase (+92.5%), suggesting unique operational dynamics or re-routing.

**Kaohsiung Port:** Demonstrates resilience across major types; Container (-1.25%), Bulk (-2.98%), and Dry Cargo (-0.97%) show only minor changes. Tanker arrivals surprisingly increase (+6.14%).

**4. Arrival Frequency Trends with Shock/Recovery**
Visualizations of monthly arrival trends confirm the quantitative findings. Red-shaded 'Shock' periods often correlate with dips in arrivals, followed by varied recovery patterns in green-shaded periods. Passenger vessels are highly volatile, while major Container and Bulk traffic in key ports tend to be more stable, with some exceptions during severe shocks.

**5. Lagged Effects and Specific Event Impact
Lagged Effects:**

Correlation between lagged oil price changes (up to 3 months) and vessel arrivals is generally weak for most vessel types. This suggests that market reactions are either immediate or driven by more complex, non-linear factors.

**Specific Events:** Geopolitical events (e.g., Hormuz Crisis, Abqaiq-Khurais Attack) have a clear and significant impact. For example, the Hormuz Crisis led to substantial drops in Bulk (-33.8%) and Dry Cargo (-43.7%). The 'Other' vessel category shows extreme volatility, with large increases or decreases depending on the event, indicating high sensitivity.

**6. Unsupervised Learning Clustering Analysis (K=4)**
Clustering of vessels based on gross_tonnage, berth_wait_hours, and vessel_type_group reveals four distinct behavioral groups:

**Cluster 0 (Mixed Short-haul & Regional Fleet):** Average tonnage ~9.7K tons, short wait (0.45 hrs). Diverse, frequent operations.

**Cluster 1 (Long-haul Giant Container Vessels):** Highest average tonnage (~103K tons), slightly longer wait (0.57 hrs). Dominated by large container ships, theoretically most sensitive to global oil prices.

**Cluster 2 (High-Efficiency Regional Containers):** Moderate tonnage (~18.5K tons), shortest wait (0.37 hrs). Optimized for rapid turnaround in regional container traffic.

**Cluster 3 (Extreme Operational Outliers):** Very small group (7 vessels), moderate tonnage (3.3K tons) but extremely long wait times (249 hours). Excluded from trend analyses due to statistical insignificance and anomalous behavior.

**7. Cluster Structure Analysis Per Port**
**Hualien:** Almost exclusively composed of Cluster 0 (99.2%), reinforcing its specialized bulk/dry cargo role.

**Taipei & Keelung:** Mix of Cluster 0, 1, and 2, but with a higher proportion of regional container (Cluster 2) traffic.

**Kaohsiung:** A balanced mix across all operational clusters, reflecting its comprehensive and diverse operations as a major international port.

**8. Oil Shock Sensitivity Analysis by Cluster**

**Cluster 0 (Mixed Short-haul):** Shows a -7.11% decline in arrivals during oil shocks, suggesting that smaller, more flexible operations are often curtailed.

**Cluster 1 (Giant Container):** Experiences a -9.32% decline, indicating that even large, essential container movements are not immune to oil price pressures.

**Cluster 2 (High-Efficiency Regional Containers):** Least impacted, with a -2.41% decrease, possibly due to their optimized operations and shorter routes.
**Cluster 3:** Excluded from this analysis due to its extreme rarity and outlier nature.
Port-specific Cluster Sensitivity:

**Hualien's Resilience Paradox:** While most clusters decline, Cluster 1 at Hualien shows a massive increase (+92.45%), but this is likely due to a very low baseline of giant vessel arrivals.

**Taipei and Keelung Vulnerability:** Both show double-digit drops in Cluster 0, indicating sensitivity in their regional traffic.

**Kaohsiung's Stability:** Continues to show the most stability across all clusters, with minor drops, cementing its role as a stable global trade hub.

**9. Lagged Effects of Oil Price Changes by Cluster**
Similar to vessel types, correlations between arrival_count and lagged oil_change for individual clusters are generally very weak (close to zero). This further supports the conclusion that direct lagged oil price movements are not strong predictors of cluster arrival frequencies.

**10. Impact of Specific Oil Shock Events by Cluster**
Specific geopolitical events cause quantifiable impacts on cluster arrivals:

**Cluster 0 (Mixed Short-haul):** Generally experiences significant negative impacts (e.g., Hormuz Crisis: -36.48% drop). Some events, like 'US-Iran Sanctions', show an increase (+10.18%), possibly due to re-routing.

**Cluster 1 (Giant Container):** Vulnerable, with declines during 'Israel-Hamas War' (-25.10%) and 'Hormuz Crisis' (-18.61%). 'US-Iran Sanctions' leads to a substantial increase (+38.54%), implying strategic redirection.

**Cluster 2 (High-Efficiency Regional Containers):** Shows mixed, often negative responses (e.g., 'Hormuz Crisis': -21.82%), but also increases during events like 'US-Iran Sanctions'.
Extreme Disruptions: Events like 'US-Israel-Iran War' led to near-complete cessation for Cluster 0 (-99.64%), highlighting severe, potentially localized, disruptions.

**11. TEU Analysis**
OLS regression on TEU (Twenty-foot Equivalent Unit) volumes shows:

**Strong Autoregressive Component:** teu_lag_1 is highly significant and positive (coef = 0.68, p < 0.001), meaning past TEU volumes are a strong predictor of current volumes.

**Oil Price Insignificance:** oil_change, oil_change_pct, and oil_shock variables are not statistically significant predictors of TEU volume (p-values > 0.05). This suggests that monthly TEU volumes, while volatile, are not directly explained by the absolute or percentage changes in oil prices, nor by the presence of a generalized oil shock in this model specification.

**Port Fixed Effects:** C(port) shows significant effects, indicating inherent differences in TEU volumes across ports (e.g., Kaohsiung has a much higher baseline).

**12. Vessel Cluster Regression Analysis**
Separate OLS regression models for Clusters 0, 1, and 2, controlling for lagged arrival counts and port fixed effects:

**Strong Autoregressive Effects:** arrival_count_lag_1 is highly significant and positive across all clusters, indicating strong persistence in arrival frequencies.

**Oil Price Changes:** oil_change (current and lagged) generally shows insignificant coefficients for most clusters, similar to the TEU analysis. There are occasional weak significances (e.g., oil_change_lag_2 for Cluster 0), but no consistent, strong, or direct impact on arrival counts.

**Oil Shock Variable:** The oil_shock dummy variable is also largely insignificant across clusters, suggesting that once lagged arrival counts and other factors are controlled, the binary 'shock' indicator itself doesn't add much explanatory power to arrival volumes.

**Port Fixed Effects:** C(port) remains significant, reflecting inherent differences in arrival baselines across ports for each cluster.

**13. ESG Correlation Heatmap: Oil vs. Idling / Emissions Proxies**
This analysis explores the potential for "Passive Decarbonization":

**Oil Price and CO₂ Proxy:** The correlation between absolute oil_price and total_co2_proxy is very weak positive (0.02). The correlation between oil_change_pct and total_co2_proxy is very weak negative (-0.02). This means higher oil prices do not strongly correlate negatively with CO₂ proxy, and a percentage change in oil price has only a minimal negative correlation.

**Traffic Volume and Emissions:** total_vessels (arrivals) is strongly positively correlated (0.97) with total_co2_proxy. This supports the idea that fewer arrivals directly lead to lower total port emissions.

**Idling Time and Emissions:** avg_berth_wait is also moderately positively correlated (0.41) with total_co2_proxy, confirming that shorter idling times reduce emissions.

**Overall Conclusions and Recommendations**

Diverse Resilience: Ports and their respective vessel traffic segments exhibit diverse sensitivities to oil price shocks and geopolitical events. Major hubs like Kaohsiung demonstrate higher resilience, while more specialized or regional ports (Taipei, Hualien, Keelung) show greater vulnerability, especially in non-essential traffic segments.

**Specific Events Drive Impact, Not General Oil Price Fluctuations:** The direct, linear correlation between oil price changes (absolute or lagged) and vessel arrivals (or TEU volumes) is weak. However, specific geopolitical oil shock events have a much more pronounced and quantifiable impact on port traffic, suggesting that market responses are driven by the nature of the disruption rather than just the price movement itself.

**Cluster-Specific Management:**
 Ports should develop strategies tailored to each cluster's characteristics and sensitivities. For instance, monitoring for Cluster 1 (Giant Container) traffic changes during global events, and optimizing turnaround for Cluster 2 (High-Efficiency Regional Containers).

**Anomaly Monitoring (Cluster 3):** Isolated operational outliers (Cluster 3) warrant dedicated, non-statistical monitoring due to their disproportionate impact on berth utilization, even if they don't reflect broader economic trends.

**Strategic Policy Implications:** Port authorities could leverage these insights to implement targeted policies, such as providing incentives for resilient vessel types, offering support for vulnerable segments during crises, and focusing on operational efficiencies to reduce berth-waiting times and emissions.
"""

